image: mephux/docker-golang
branches:
  - master
  - develop
git:
  path: github.com/mephux/envdb
script:
  - go get github.com/jteeuwen/go-bindata/...
  - go get github.com/elazarl/go-bindata-assetfs/...
  - make
  - ./bin/envdb --version
  - make package
notify:
  email:
    recipients:
      - dustin.webber@gmail.com
publish:
  github:
    branch: master
    script:
    artifacts:
      - release
    tag: v$(cat .Version)
    token: $$GITHUB_TOKEN
    user: mephux
    repo: envdb
    when: 
      branch: master
      pull_requests: false
